### ISSUE TITLE
Failed to import Liveportrait

### ISSUE THREAD

**Issue by fdupas67** [kijai/ComfyUI-LivePortraitKJ#109]
Since some days, my Liveportrait doesn't work anymore so I wanted to reinstall it and I have always the same mistake when I try to import Liveportrait from the ComfyUI manager. I have also tried with git clone but always the same probleme. Someone has an idea about it ?

![LivePortraitError](https://github.com/user-attachments/assets/773d4030-8fd6-45d0-b53c-08cb6415204a)

**Comment by kijai** [comment]
> Since some days, my Liveportrait doesn't work anymore so I wanted to reinstall it and I have always the same mistake when I try to import Liveportrait from the ComfyUI manager. I have also tried with git clone but always the same probleme. Someone has an idea about it ?
> 
> ![LivePortraitError](https://private-user-images.githubusercontent.com/72316226/353622487-773d4030-8fd6-45d0-b53c-08cb6415204a.JPG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIzNzU1MjUsIm5iZiI6MTcyMjM3NTIyNSwicGF0aCI6Ii83MjMxNjIyNi8zNTM2MjI0ODctNzczZDQwMzAtOGZkNi00NWQwLWI1M2MtMDhjYjY0MTUyMDRhLkpQRz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzMwVDIxMzM0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc5NThiYWFmZjcwMWE2ZmJiOTJlZWU2Y2EyZjdlY2MzZDVmZWE3M2E1Y2ZiMmQ3OGEwYjI2MTU2Y2VjOWM4NTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ByiVAOCGN8ANw1gi2SMGcXUxtFz_B4D5EmNJU3gFUZQ)

That node shown there is not this node pack, it's another one: https://github.com/shadowcz007/comfyui-liveportrait

This one is:

![image](https://github.com/user-attachments/assets/9b4057e4-4bec-4114-994c-9e5bd3490eb7)

**Comment by fdupas67** [comment]
I will try it. I dind't saw that it was the wrong node pack. Thank you very much.

**Comment by fdupas67** [comment]
Now it works again. It is probably because I have insisted trying to install the wrong node. 👍 Thank you for your help.
