### ISSUE TITLE
!!! Exception during processing!!! [Errno 2] No such file ./utils/resources/mask_template.png'

### ISSUE THREAD

**Issue by whmc76** [kijai/ComfyUI-LivePortraitKJ#11]
!!! Exception during processing!!! [Errno 2] No such file or directory: 'E:\\IMAGE\\ComfyUI_master\\ComfyUI\\custom_nodes\\ComfyUI-LivePortraitKJ\\liveportrait\\./utils/resources/mask_template.png'
Traceback (most recent call last):
  File "E:\IMAGE\ComfyUI_master\ComfyUI\execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\IMAGE\ComfyUI_master\ComfyUI\execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\IMAGE\ComfyUI_master\ComfyUI\execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\IMAGE\ComfyUI_master\ComfyUI\custom_nodes\ComfyUI-LivePortraitKJ\nodes.py", line 260, in process
    cropped_frames, full_frame = pipeline.execute(img, driving_images_np)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\IMAGE\ComfyUI_master\ComfyUI\custom_nodes\ComfyUI-LivePortraitKJ\liveportrait\live_portrait_pipeline.py", line 97, in execute
    inference_cfg.mask_crop = cv2.imread(make_abs_path('./utils/resources/mask_template.png'), cv2.IMREAD_COLOR)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\IMAGE\ComfyUI_master\python_embeded\Lib\site-packages\ultralytics\utils\patches.py", line 26, in imread
    return cv2.imdecode(np.fromfile(filename, np.uint8), flags)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'E:\\IMAGE\\ComfyUI_master\\ComfyUI\\custom_nodes\\ComfyUI-LivePortraitKJ\\liveportrait\\./utils/resources/mask_template.png'

**Comment by cyco-creates** [comment]
Same for me!

**Comment by xiety** [comment]
In my case, something was wrong in git lfs and some files were not pulled when cloning. I downloaded this repository as a .zip and extracted it into custom_nodes folder

**Comment by xiety** [comment]
I've cloned original repo `https://github.com/KwaiVGI/LivePortrait` and I took `mask_template.png` file from there

**Comment by 3blackbar** [comment]
yeah that solves all the issues i had as well

**Comment by whmc76** [comment]
> I've cloned original repo `https://github.com/KwaiVGI/LivePortrait` and I took `mask_template.png` file from there

 great bro

**Comment by dancemanUK** [comment]
> I've cloned original repo `https://github.com/KwaiVGI/LivePortrait` and I took `mask_template.png` file from there
> 
> Link to file: https://github.com/KwaiVGI/LivePortrait/blob/main/src/utils/resources/mask_template.png

Thank you! brother!

**Comment by kijai** [comment]
This should now be fixed, was caused by the mask_template.png not being cloned correctly. Might need to re clone the node files if just updating doesn't work.
