### ISSUE TITLE
ValueError: The number of driving images should be larger than the number of source images.

### ISSUE THREAD

**Issue by O-O1024** [kijai/ComfyUI-LivePortraitKJ#120]
If the frame count of driving video is less than frame_load_cap, 

![image](https://github.com/user-attachments/assets/7221a1db-ca5b-4731-819a-949c9b0b6afb)

this error will be raised:
```
Traceback (most recent call last):
  File "/root/ComfyUI/execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "/root/ComfyUI/execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "/root/ComfyUI/execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "/root/ComfyUI/custom_nodes/ComfyUI-LivePortraitKJ/nodes.py", line 317, in process
    raise ValueError("The number of driving images should be larger than the number of source images.")
ValueError: The number of driving images should be larger than the number of source images.
```

😳 Is it necessary ? Why don't choose the same strategy like the official repo [the 3th point](https://github.com/KwaiVGI/LivePortrait/blob/main/assets/gradio/gradio_description_animation.md) ?

**Comment by kijai** [comment]
Rude? I find it the opposite, rude would be to assume the user knows of this limitation and leave them wondering why is it not working. You can easily limit the frame load cap of the source as well with that same value.

**Comment by O-O1024** [comment]
En en, yes. But I don't know how many frames the video contains before runing workflows to get this info, and VideoHelperSuit node doesn't provider it. @Kosinkadink
