### ISSUE TITLE
Node not displayed ImageConcatMulti

### ISSUE THREAD

**Issue by iovart** [kijai/ComfyUI-LivePortraitKJ#14]
how to install the node? 
![Desktop 05-07-2024 16-55-51-262](https://github.com/kijai/ComfyUI-LivePortraitKJ/assets/157212332/f73aca09-a8ae-4f7f-ad32-df1d9b2beff1)

**Comment by xiety** [comment]
This node is in https://github.com/kijai/ComfyUI-KJNodes

But you can remove it from this workflow. It is used only to create side-by-side video with original.

**Comment by iovart** [comment]
> This node is in https://github.com/kijai/ComfyUI-KJNodes
> 
> But you can remove it from this workflow. It is used only to create side-by-side video with original.

Thanks!

**Comment by kijai** [comment]
Yes it's relatively new node in KJNodes, so updating that pack should fix it. It's also not necessary at all like mentioned, safe to delete and just use single image output.

**Comment by iovart** [comment]
> Yes it's relatively new node in KJNodes, so updating that pack should fix it. It's also not necessary at all like mentioned, safe to delete and just use single image output.

Thanks!
