### ISSUE TITLE
Get error when using "LivePortrait Retargeting" node 

### ISSUE THREAD

**Issue by SofiaRin** [kijai/ComfyUI-LivePortraitKJ#154]
hi, I encountered an error while trying to use the LivePortrait Retargeting node. I have attached the error log and a screenshot of the workflow. I would appreciate your help and guidance.

```
Error occurred when executing LivePortraitProcess:

list index out of range

File "D:\Test\stablediff\ComfyUI\execution.py", line 151, in recursive_execute
output_data, output_ui = get_output_data(obj, input_data_all)
File "D:\Test\stablediff\ComfyUI\execution.py", line 81, in get_output_data
return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
File "D:\Test\stablediff\ComfyUI\execution.py", line 74, in map_node_over_list
results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
File "D:\Test\stablediff\ComfyUI\custom_nodes\ComfyUI-LivePortraitKJ\nodes.py", line 349, in process
out = pipeline.execute(
File "D:\Test\stablediff\ComfyUI\custom_nodes\ComfyUI-LivePortraitKJ\liveportrait\live_portrait_pipeline.py", line 228, in execute
c_d_lip_i = calc_lip_close_ratio(driving_landmarks[i][None])
```
![Snipaste_2024-11-07_20-55-53](https://github.com/user-attachments/assets/6d908d76-3d64-4623-8140-418a49568326)

**Comment by AzmaeenAdil** [comment]
Damn, just now searched it, and found your question, that is the same case for me.

**Comment by SofiaRin** [comment]
I found the problem: the Retargeting Node needs to be linked to the driving video, but I mistakenly connected it to the source image. Since the source image is a single frame, it caused an out-of-bounds access.

> Damn, just now searched it, and found your question, that is the same case for me.

**Comment by poopsock12** [comment]
> I found the problem: the Retargeting Node needs to be linked to the driving video, but I mistakenly connected it to the source image. Since the source image is a single frame, it caused an out-of-bounds access.
> 
Can u send a screenshot or something idk what you mean
