### ISSUE TITLE
Hallo Node implementation

### ISSUE THREAD

**Issue by kakachiex2** [kijai/ComfyUI-LivePortraitKJ#23]
Hi Kijai, sorry for posting this here, I would like to see a Hallo node implementation by you for comfyui the implemented one for comfy are hell as slow but all your implementation are fast.
https://github.com/fudan-generative-vision/hallo

**Comment by 3blackbar** [comment]
https://github.com/AIFSH/ComfyUI-Hallo

**Comment by kakachiex2** [comment]
I have this one is super slow it took 2 hour to generate the first pass

**Comment by 3blackbar** [comment]
what gpu

**Comment by kakachiex2** [comment]
RTX260 6gb VRamm

**Comment by kakachiex2** [comment]
I have tested lots of implementation from others dev and all the one that works in my machine are from Kijai, men Kijai is excellent at coding I don't know what he does but all his node works excellent and fast.

**Comment by kakachiex2** [comment]
Wen, I see what Illyasviel do with forge old tech hardware work 80, 90% faster than the new one this is a really good optimization in forge. So everything is possible with experimentation and creativity even in code creativity is important.
