### ISSUE TITLE
Output based on self-recorded videos with stable webcam coming off very shaky

### ISSUE THREAD

**Issue by zahdab** [kijai/ComfyUI-LivePortraitKJ#26]
I tried capturing videos with webcam with shoulders being very still... 
I am getting very shaky results like a shivering, other instances the head would start scaling up and down. 
any idea what i am doing wrong ?

**Comment by kijai** [comment]
Did you crop the video to only the face? And have you checked the example videos in the /assets/examples/driving -folder?

**Comment by zahdab** [comment]
Hello i tried cropping to my face, and tried shooting the video in the morniing with better light conditions and used NVIDEA broadcast to remove the background... 
it's way better now. thanks
