### ISSUE TITLE
Installation is not allowed in this security_level

### ISSUE THREAD

**Issue by txirrindulari** [kijai/ComfyUI-LivePortraitKJ#27]
Can you make this add-on accomplish the new security issues in ComfyUI?

ComfyUI-LivePortraitKJ install failed: With the current security level configuration, only custom nodes from the "default channel" can be installed.

**Comment by kijai** [comment]
I have no idea about that, last time it happened it just took few days to clear.

**Comment by Burve** [comment]
I got the same problem few minutes ago, and for me Updating all (including Manager plugin) fixed this error.

**Comment by kijai** [comment]
It's most likely about Manager version itself yeah, updating that should fix it.

**Comment by txirrindulari** [comment]
Beautiful! It is working now after update all. 
It is kind of weird because I had just done a clean install.
Thank you
Great project!
