### ISSUE TITLE
Node for sadtalker

### ISSUE THREAD

**Issue by shivshankar11** [kijai/ComfyUI-LivePortraitKJ#3]
Hi, a comfyui nodes for sadtalker too will be pretty cool. Have you looked into sadtalker?

**Comment by kijai** [comment]
Hey, I have seen it, but currently I don't have time to look into it further and it's out of scope for this project.

**Comment by GamingDaveUk** [comment]
Found this issue when searching for a Sadtalker node. 
I have a ton of sound files I want to turn into talking avatars video's, Bio's for a guild I am in.
So far online methods are capped at 30 seconds and all nodes I have seen need a video to do the lipsync from. 
So if I could plus one this request, even if its a long time away before you even look to do it, as there really isnt an alternative available (that I have found)

**Comment by kijai** [comment]
> Found this issue when searching for a Sadtalker node. I have a ton of sound files I want to turn into talking avatars video's, Bio's for a guild I am in. So far online methods are capped at 30 seconds and all nodes I have seen need a video to do the lipsync from. So if I could plus one this request, even if its a long time away before you even look to do it, as there really isnt an alternative available (that I have found)

Check out this project, brand new, might work on it for Comfy if no one else does at some point: https://badtobest.github.io/echomimic.html

**Comment by GamingDaveUk** [comment]
> > Found this issue when searching for a Sadtalker node. I have a ton of sound files I want to turn into talking avatars video's, Bio's for a guild I am in. So far online methods are capped at 30 seconds and all nodes I have seen need a video to do the lipsync from. So if I could plus one this request, even if its a long time away before you even look to do it, as there really isnt an alternative available (that I have found)
> 
> Check out this project, brand new, might work on it for Comfy if no one else does at some point: https://badtobest.github.io/echomimic.html

stumbled on that not long after posting the reply above. Have asked on their tracker if a comfyui node is available. Didnt notice how new it is though https://github.com/BadToBest/EchoMimic/issues/4 

The LLMVISION stuff has me a bit nervous of non safetensor models though (I dont fully know enough of about the models to know fully whats safe though, atleast now comfyui does a safety check on start, would love to see a node for echomimic if at all possible (assuming one doesnt exist)
