### ISSUE TITLE
video upload dont 

### ISSUE THREAD

**Issue by tryx78** [kijai/ComfyUI-LivePortraitKJ#30]
the possibility to upload the video does not appear, can someone help me? thank you very much
<img width="500" alt="Screenshot 2024-07-06 alle 19 15 37" src="https://github.com/kijai/ComfyUI-LivePortraitKJ/assets/136930363/8e517d9e-adc5-440e-9f50-89337c4d8a8d">

**Comment by melMass** [comment]
You probably want the `Load Video (Upload)` node. This one is for **(Path)**.
If you have further issues with that node it should be reported to the corresponding project: https://github.com/Kosinkadink/ComfyUI-VideoHelperSuite
