### ISSUE TITLE
Deformed result with LivePortrait

### ISSUE THREAD

**Issue by kakachiex2** [kijai/ComfyUI-LivePortraitKJ#32]
I test a lot of videos but get the same deformed result the original model example is really good did I did something wrong.
- the image needs a specific ratio and the video
- What is the requirement for the image and video in size, cropped area etc...

https://github.com/kijai/ComfyUI-LivePortraitKJ/assets/1762112/f9a6ed4a-465f-4761-997b-49955c2762b5

**Comment by kakachiex2** [comment]
Kijai as always great adaptation this process fast in my computer, great works thanks so much.

**Comment by kakachiex2** [comment]
Ok it don't like head movement only face expression I use the same videos from the official GitHub and this is the result nice.

https://github.com/kijai/ComfyUI-LivePortraitKJ/assets/1762112/d655582d-44a2-48f9-9c3d-94710c92e33f

**Comment by kakachiex2** [comment]
But in the official project I see some example with head movement really clean and accurate

**Comment by tryx78** [comment]
@kakachiex2 how to fix deformed result? i have same problem

thanks

**Comment by kijai** [comment]
> But in the official project I see some example with head movement really clean and accurate

If you refer to the video edit, they haven't released the code yet. Overall it's a bit strict on the quality and structure of the driving video, the included examples work great and should be used as guideline.

**Comment by kakachiex2** [comment]
Use videos with clean background and less head movement for now try with the official videos

**Comment by kakachiex2** [comment]
This is another test

https://github.com/kijai/ComfyUI-LivePortraitKJ/assets/1762112/6517fc4d-b713-461b-89b8-c05f300c5654

**Comment by kakachiex2** [comment]
If your video has sound to match it perfectly in CapCut you need to give the same FPS in this case 30.

**Comment by kijai** [comment]
Bobbing head issue is now fixed.
