### ISSUE TITLE
Retargeting makes the face stuck 

### ISSUE THREAD

**Issue by fusillustrator** [kijai/ComfyUI-LivePortraitKJ#35]
I dont get whats the point of eye retargeting and lips retargeting when it clearly doesnot work at all and makes the face stuck . I am so confused , can you clarify or is this feature under construction?

**Comment by kijai** [comment]
It's somewhat under construction as it's mostly useful for video editing, feature they didn't release code for yet. If you change the "relative" mode it should allow head movement with them on already though.
