### ISSUE TITLE
ERROR RUNNING THE EXAMPLE: TypeError: Cannot read properties of undefined (reading 'clientId')

### ISSUE THREAD

**Issue by barshag** [kijai/ComfyUI-LivePortraitKJ#39]

**Comment by kijai** [comment]
Gonna need more info than that.

**Comment by coeuskoalemoss** [comment]
WHAAAAAAAAAAAAAAAAAAAAAA

**Comment by coeuskoalemoss** [comment]
@kijai why is this closed?

**Comment by kijai** [comment]
> @kijai why is this closed?

Because there's zero information here? I don't know what I'm supposed to do with this.

**Comment by coeuskoalemoss** [comment]
I kinda have a solution
