### ISSUE TITLE
Conflicting Modes? Or missing?

### ISSUE THREAD

**Issue by Merzmensch** [kijai/ComfyUI-LivePortraitKJ#44]
Hi there, after I LivePortrait installed via  ComfyUI Manager, and also out insightface files to "\ComfyUI\models\insightface\buffalo_l" I still miss the nodes.

In the description of LivePortrait (Manager) I see following:

Conflicted Nodes:
DownloadAndLoadLivePortraitModels [ComfyUI-LivePortraitKJ-MPS], LivePortraitProcess [ComfyUI-LivePortraitKJ-MPS]

What shall I do? I am using Portable ComfyUI.

Thank you,
best regards,
Merzmensch

**Comment by kijai** [comment]
Delete the ComfyUI-LivePortraitKJ-MPS, it's a fork for mac version and shouldn't be needed anymore anyway.

**Comment by Grant-CP** [comment]
@kijai The current develop branch and main branch both do not work without `PYTORCH_ENABLE_MPS_FALLBACK=1`. I think before totally removing my repo one of the following should happen:
1. (Easiest for now) A part of the README here mentions how to set an environment variable `var python main.py` where `main.py` is the comfyui executable. Putting a print statement with what to do and auto-failure after detecting MPS would also work well.
2. (Preferred) My changes from the other thread to manually swap tensors on a few operations on `NotImplementedError` get added. Let me know if a pull request (on main or develop?) would help.

I'll raise an issue in the main manager repo to start my node getting delisted. Hopefully ltdrdata will also give some insight on how it got added in the first place.
