### ISSUE TITLE
Not an issue but for everybody that has problems with Insightface

### ISSUE THREAD

**Issue by DerHaider420** [kijai/ComfyUI-LivePortraitKJ#45]
Download a FRESH ComfyUI portable

When installing (even when run as admin) use

python_embeded/python.exe -m pip install --user insightface  

instead of

python_embeded/python.exe -m pip install insightface

(The --user part is lacking in the Instructions)

**Comment by melMass** [comment]
That's not the recommended way as this would install it "globally" for the user's given Python version (in the user directory) and can introduce hard-to-debug issues.


On windows depending on the portable comfy you use:

```sh
# for python 3.10
python_embeded/python.exe -m pip install https://github.com/Gourieff/Assets/raw/main/Insightface/insightface-0.7.3-cp310-cp310-win_amd64.whl
# for python 3.11
python_embeded/python.exe -m pip install https://github.com/Gourieff/Assets/raw/main/Insightface/insightface-0.7.3-cp311-cp311-win_amd64.whl
# for python 3.12
python_embeded/python.exe -m pip install https://github.com/Gourieff/Assets/raw/main/Insightface/insightface-0.7.3-cp312-cp312-win_amd64.whl
```
