### ISSUE TITLE
RuntimeError: PyTorch is not linked with support for mps devices

### ISSUE THREAD

**Issue by LSI86** [kijai/ComfyUI-LivePortraitKJ#47]
Please, what about it?

[22:23:04] FaceAnalysisDIY warmup time: 1.731s                                                   face_analysis_diy.py:79
!!! Exception during processing!!! PyTorch is not linked with support for mps devices
Traceback (most recent call last):
  File "C:\Comfyui\ComfyUI\execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Comfyui\ComfyUI\execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Comfyui\ComfyUI\execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Comfyui\ComfyUI\custom_nodes\ComfyUI-LivePortraitKJ-MPS\nodes.py", line 260, in process
    cropped_frames, full_frame = pipeline.execute(img, driving_images_np)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Comfyui\ComfyUI\custom_nodes\ComfyUI-LivePortraitKJ-MPS\liveportrait\live_portrait_pipeline.py", line 50, in execute
    I_s = self.live_portrait_wrapper.prepare_source(img_crop_256x256)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Comfyui\ComfyUI\custom_nodes\ComfyUI-LivePortraitKJ-MPS\liveportrait\live_portrait_wrapper.py", line 63, in prepare_source
    x = x.to(self.device)
        ^^^^^^^^^^^^^^^^^
RuntimeError: PyTorch is not linked with support for mps devices

**Comment by kijai** [comment]
> @kijai In the future if I fork things for implementing MPS support do you want me to rename them better? I assumed that people on windows would not install the Apple Silicon version of a node.
> 
> After we get MPS support in this repo (I've read your changes but not tested them yet) I can set my repo up to give a fatal error that says they should download your node instead. It's my first time pushing edits to a comfy node so sorry if I made extra work from you.
> 
> I've added a assert message with a failure in my node to tell them to download yours instead if mps is not available, although that will only affect people who have an up-to-date version of the node.

I don't care about the naming, you're free to do whatever you want on GitHub, and I appreciate the help with this issue. I do have bit of a problem with it being in the Manager though, I don't know if it was you who added it there? People installing from git probably understand the difference between repos, Manager users mostly don't seem to.

**Comment by kijai** [comment]
> > Why is everyone suddenly installing the MPS version? That is not this repository. Are using a Mac?
> 
> Intel i7, RTX 3070 and Windows 11 64bit I was running this workflow (COMFYUI): [https://openart.ai/workflows/datou/live-portrait/PMM4NSLnbhU08xvRqN2e](url)

Yeah they are mac user then, you can just delete the MPS version and install this one.

**Comment by Grant-CP** [comment]
@kijai I had no idea it was in the manager. And of course it lists every single one of your nodes as a conflict. I suspect we will be able to nuke my repo soon.

That's kind of crazy that they added it that fast. I got a pull request from comfy-org to put it in the main registry but did not accept. I replied to their pull request saying I don't think it should be in the registry but they haven't replied.

I've updated the README on my repo to start with a link to your repo, so at least whenever the manager pulls the latest commits the message for my node will show.

I wonder if openart automatically adds nodes to the manager, or if someone from comfy-org is scraping and auto-adding repos. I imagine the registry is an attempt to solve problems like this.

**Comment by Grant-CP** [comment]
@kijai I found the commit I think: https://github.com/ltdrdata/ComfyUI-Manager/commit/625e3e84f48aabd950bb007197cf60d376abb96f

You can find my node by searching "-mps". I'm no git expert, but it looks like this was not a pull request but ltdrdata updating the DB with whatever they are doing on the backend? Looks like a lot of nodes are being added that way

**Comment by LSI86** [comment]
Thank you I deleted the nodes, installed git directly from here and everything works. Thank you for your advice
