### ISSUE TITLE
[feature] Insight face stays loaded after generation

### ISSUE THREAD

**Issue by LubuLubu2** [kijai/ComfyUI-LivePortraitKJ#53]
Hi Kijai, thank you for your amazing nods <3

Is there a way that Insightface don't unload after generation ? it might not be a problem for most people but my Insight face is somehow broken (if i fix it, it break some other nods :D ) it take around 100seconds to just load insightface, the video generation 20second. each time i change the picture or video it starts to load insightface again (100seconds wait).

For example in IPAdapter or FaceID it only loads insightface one time, after that you can change images and it stays loaded until you close comfy or clear workflow.

**Comment by kijai** [comment]
> Hi Kijai, thank you for your amazing nods <3
> 
> Is there a way that Insightface don't unload after generation ? it might not be a problem for most people but my Insight face is somehow broken (if i fix it, it break some other nods :D ) it take around 100seconds to just load insightface, the video generation 20second. each time i change the picture or video it starts to load insightface again (100seconds wait).
> 
> For example in IPAdapter or FaceID it only loads insightface one time, after that you can change images and it stays loaded until you close comfy or clear workflow.

Yeah that's all done in the develop version already, still fixing some bugs and testing as it's a huge update that separates the detection part to it's own node too.

**Comment by LubuLubu2** [comment]
superb, thank you
