### ISSUE TITLE
Feature request: Face index selection and multiple face inputs. 

### ISSUE THREAD

**Issue by bigandtallrecords** [kijai/ComfyUI-LivePortraitKJ#65]
Hey there great work! 
Got this thing cooking. But would really love to select a single subject in a group similar to the React nodes index selection going from left to right top to bottom I think. And a separate input for individual driver sequences would be great.  The idea being to put many performances on many faces with one pass with image sequences. 
Thank you! 
Daniel

**Comment by kijai** [comment]
The version in develop branch already has face index selection, it's left at default for now which is largest-smallest order.

**Comment by bigandtallrecords** [comment]
Nice! Looking forward to it! Also wondering if there was any way to get a larger canvas size. Currently for a 4k video the video gets sized down to 1280x720. Would love the ability to keep that at around 1080p. And possibly a larger face size onnx like the 2048 react with this. Not sure if thats even possible just thinking out loud. Thank you again for your work!

**Comment by kijai** [comment]
Merged to main.
