### ISSUE TITLE
LivePortrait Croper ＆KeypointsToImage missing!

### ISSUE THREAD

**Issue by kentaro001** [kijai/ComfyUI-LivePortraitKJ#66]
When using this sample workflow, an error occurred where the LivePortrait Cropper and Keypoints To Image nodes could not be found
https://github.com/kijai/ComfyUI-LivePortraitKJ/tree/develop/examples

![スクリーンショット 2024-07-13 120719](https://github.com/user-attachments/assets/287ba59d-4f7a-44e8-a7dd-3cb985805780)

The common error due to InsightFace not being downloaded has been resolved, and i2v is possible, but v2v is not working

**Comment by morvenshen** [comment]
How did you solve the problem of missing modules? This has troubled me for several days.

**Comment by Quasimondo** [comment]
You will have to switch to the development branch by going into the custom_nodes/ComfyUI-LivePortraitKJ folder in a terminal and then do
git switch origin/develop

(This assumes that you had originally checked out the repo via git)

**Comment by babamallorca** [comment]
I tried that, but I get the following error: 

fatal: a branch is expected, got remote branch 'origin/develop'
hint: If you want to detach HEAD at the commit, try again with the --detach option.

What can I do? thanks

**Comment by kijai** [comment]
> I tried that, but I get the following error: 
> 
> fatal: a branch is expected, got remote branch 'origin/develop'
> hint: If you want to detach HEAD at the commit, try again with the --detach option.
> 
> What can I do? thanks

```git fetch --all
git switch develop```

**Comment by kijai** [comment]
> > I tried that, but I get the following error: 
> > 
> > fatal: a branch is expected, got remote branch 'origin/develop'
> > hint: If you want to detach HEAD at the commit, try again with the --detach option.
> > 
> > What can I do? thanks
> 
> `git fetch --all`
> `git switch develop`

**Comment by babamallorca** [comment]
I have fixed it with: git switch origin/develop --detach

Thanks!

**Comment by kijai** [comment]
Ok, whatever works...this is only temporary, I'm away from any PC for a while (taking a break), which is why I haven't merged this to main yet. There are couple of bugs and some refactoring to do before it's ready (or at least as ready as any of this stuff will ever be)

**Comment by Amit30swgoh** [comment]
who to do it using Comfyui-manager and running it via google Colab please

> Ok, whatever works...this is only temporary, I'm away from any PC for a while (taking a break), which is why I haven't merged this to main yet. There are couple of bugs and some refactoring to do before it's ready (or at least as ready as any of this stuff will ever be)

what to do it using Comfyui-manager and running it via google Colab please

**Comment by kijai** [comment]
Develop nodes now merged to main.
