### ISSUE TITLE
How to solve LivePortrait Croper ＆KeypointsToImage missing？It's been bothering me for days.

### ISSUE THREAD

**Issue by morvenshen** [kijai/ComfyUI-LivePortraitKJ#70]
![微信截图_20240714213522](https://github.com/user-attachments/assets/57edf463-81b0-4389-8bc4-922b0b43200b)
Unable to find the corresponding installation node, I don’t know what the problem is

**Comment by kijai** [comment]
Those nodes are only available in the development branch currently.
