### ISSUE TITLE
A way to get better results for vid2vid

### ISSUE THREAD

**Issue by henjicc** [kijai/ComfyUI-LivePortraitKJ#72]
I used the develop branch to create the vid2vid effect, and after some testing I realized that vid2vid works better if the mouth of the source video is closed, and not so well if the mouth of the source video is open and changes all the time.

**So we can use Retargeting to close the mouth of the source video, which should give us a better result, but this node doesn't seem to be able to do that at the moment. I've found that the Retargeting part of the original project can do it (i.e., the Retargeting function at the bottom of the app.py), so it would be nice to add that function to this node, so that we can use it in the current one. node, that would be great!
Another thing is that whether the eyes are closed or not doesn't seem to have a big effect on the final result, so it would be better to handle the mouth in a way that doesn't affect the eyes, which the current function in app.py does, and this can get very strange if there is eye movement.**

I've tried lip_retargeting in LivePortraitProcess and it doesn't achieve a similar effect, if it does, please tell me the correct procedure!

---

> **The English above is translated from the Chinese below.**
> 我使用 develop 分支来创建 vid2vid 效果，经过测试我发现，如果原视频的嘴部是闭合的，那么 vid2vid 的效果就会比较好，反之，如果原视频的嘴部是张开的并且是一直变化的，那么效果就不太好。
> 所以我们可以使用 Retargeting 来闭合原视频的嘴部，这样能应该能获得更好的效果，但是目前这个节点好像无法实现这个功能。我发现原项目的 Retargeting 部分是可以做到的（也就是 app.py 最底部的Retargeting功能），所以如果能在当前这个节点上添加这个功能，那就太好了！
> 另外还有一点，就是眼睛是否闭合，对最终效果影响似乎不是很大，所以最好在处理嘴部的时候，能不影响到眼睛，目前 app.py 里的这个功能是会影响到眼睛的，如果眼部有运动的话，这会变得非常奇怪。
> 我尝试过 LivePortraitProcess 的 lip_retargeting，并不能实现类似效果，如果可以的话，请告诉正确的操作步骤

![image](https://github.com/user-attachments/assets/6aec0565-1f17-4784-9463-37d1af626c48)

**Comment by vienduong88** [comment]
This is exactly what I'm trying to do, would be nice if we can have a retarget node for video.

**Comment by kijai** [comment]
The video processing is now much better in the develop branch, new relative_only -mode or smoothed video mode should take care of that.

**Comment by henjicc** [comment]
> The video processing is now much better in the develop branch, new relative_only -mode or smoothed video mode should take care of that.

Thank you very much! I will try it.
