### ISSUE TITLE
[feature request] Expose face direction

### ISSUE THREAD

**Issue by melMass** [kijai/ComfyUI-LivePortraitKJ#75]
This here:
https://github.com/kijai/ComfyUI-LivePortraitKJ/blob/2a7bd6116f32e99d3a40057eac222c3666c1dfb1/liveportrait/utils/face_analysis_diy.py#L28-L46

Defines how the index behaves. Currently, it defaults to `large-small` meaning 0 is the biggest face in the frame, and subsequent indexes are smaller faces... This should probably either default to `left-right` or be exposed

**Comment by kijai** [comment]
Should be exposed in my opinion, large-small as default makes sense in single face scenarios as you generally want to target the main face, while left-right probably makes most sense when doing multiple faces.
