### ISSUE TITLE
Settings do not work.

### ISSUE THREAD

**Issue by Dunc4n1dah0** [kijai/ComfyUI-LivePortraitKJ#76]
So... I tested all of those (wasted time) and none of settings in pasted image work, like they are hardcoded. Generated videos are just identical.

dsize - no effect
scale - no effect
vx ratio - no effect
vy ratio - no effect

Why to even show settings that are hardcoded?

<img width="313" alt="image" src="https://github.com/user-attachments/assets/256b2cb3-921f-4cf1-9e22-8bb668d23430">

**Comment by kijai** [comment]
> So... I tested all of those (wasted time) and none of settings in pasted image work, like they are hardcoded. Generated videos are just identical.
> 
> dsize - no effect
> scale - no effect
> vx ratio - no effect
> vy ratio - no effect
> 
> Why to even show settings that are hardcoded?
> 
> <img width="313" alt="image" src="https://github.com/user-attachments/assets/256b2cb3-921f-4cf1-9e22-8bb668d23430">
> 

I don't know, I just initially exposed the arguments that they had, turns out many didn't do anything. Most of them work properly in the development branch version already.

**Comment by Dunc4n1dah0** [comment]
I switched to dev branch, still I don't see any changes to produced video... only thing I noticed is that output files differ by few kB (on main branch too) when I change those settings, or it can be nature of SD, but no visual change.  Maybe those parameters don't do too much. We need more testing.

**Comment by kijai** [comment]
All of the cropper settings now work, as demonstrated in the new realtime example video.
