### ISSUE TITLE
Incorrect wording in develop branch

### ISSUE THREAD

**Issue by Inferencer** [kijai/ComfyUI-LivePortraitKJ#77]
Error states 
driving images should be larger than the number of source images

But my source was 16secs and my driving was over 25secs

When I switched them around so I uploaded my source as driving and my driving as source it worked
which means error should have stated source images should be larger than the number of driving images

Source being the target and driving being the controller

**Comment by kijai** [comment]
> Error states 
> driving images should be larger than the number of source images
> 
> But my source was 16secs and my driving was over 25secs
> 
> When I switched them around so I uploaded my source as driving and my driving as source it worked
> which means error should have stated source images should be larger than the number of driving images
> 
> Source being the target and driving being the controller 

It's about the frame count you load, your videos probably have different frame rates. Driving frames will always need to be at least as many as source frames, or more.

**Comment by Inferencer** [comment]
same frame rates but not the issue as I confirmed my frame count when I received the error, my point is the error is confusing driving frames with source frames in the error message, 
as mentioned the source video should be the target video (the video that will be animated) and driving video is the one we use to get the features but in the case of the develop branch it's the source video that needs more frames than the driving video not the other way around so not sure if that's a coding error from you mistakenly switching their limits around.
