### ISSUE TITLE
LivePortraitCropper - No Face Detected Error

### ISSUE THREAD

**Issue by SWAPv1** [kijai/ComfyUI-LivePortraitKJ#78]
Hello,
I am getting a No Face Detected Error probably because the face gets obscured on a few frames by the hand waving in front of it. 
Is there a way that it can just skip those frames instead of erroring out? Otherwise I suppose I could divide the video into sections.

Thank you.

**Comment by kijai** [comment]
On the dev branch this is handled better now.
