### ISSUE TITLE
Portrait video editing with stitching option ?

### ISSUE THREAD

**Issue by 3blackbar** [kijai/ComfyUI-LivePortraitKJ#8]
In their example you can load input video, and just drive the mouth and eyes in the video, so it works with full video not just one image
https://liveportrait.github.io/
 https://liveportrait.github.io/src/video/video_animation_0_opt.mp4

**Comment by kijai** [comment]
Either I'm missing something or they didn't include the code for this. Unless it's the template option which I don't yet understand.

**Comment by 3blackbar** [comment]
ok, heres how it can be done, instead of feeding the node the same image, how about you feed frame from another video per each new frame ? So you have video feed as input, frames too , cause in "relative" mode its using whole input image, so in theory it should be able to use different image per every frame and not just one image ?

**Comment by JZZZ1314** [comment]
I was able to perform a simple test, and by inferring about each frame of the edited video by talking about each frame of the driving video, I was able to get an effect close to that of the paper，Of course, this needs to wait for the official release of the full code, which is only experimental

**Comment by ozworkz** [comment]
> ok, heres how it can be done, - in relative mode wth source video input under source image input, so instead of feeding the node the same image, how about you feed frame from another video per each new frame ? So you have video feed as input frames too, face aligner should detect where the face is per new frame. Turn off retageting and enable relative mode ,cause in "relative" mode its using whole input image and its using one image for entire video, im sure this can be changed so its using consecutive video frames instead of one image , so in theory it should be able to use different image per every frame and not just one image ?
> 
> With this working we will be able to change what people say on the videos.

Yes, with some tweaks in the code, reading each frame from the video input as a source image seems to work. Thanks!

**Comment by 3blackbar** [comment]
Can You guys do pull request if You succesfully did it ?

**Comment by Trimad** [comment]
> > ok, heres how it can be done, - in relative mode wth source video input under source image input, so instead of feeding the node the same image, how about you feed frame from another video per each new frame ? So you have video feed as input frames too, face aligner should detect where the face is per new frame. Turn off retageting and enable relative mode ,cause in "relative" mode its using whole input image and its using one image for entire video, im sure this can be changed so its using consecutive video frames instead of one image , so in theory it should be able to use different image per every frame and not just one image ?
> > With this working we will be able to change what people say on the videos.
> 
> Yes, with some tweaks in the code, reading each frame from the video input as a source image seems to work. Thanks!

Can you post your ComfyUI workflow please?

**Comment by serkandyck** [comment]
> > > ok, heres how it can be done, - in relative mode wth source video input under source image input, so instead of feeding the node the same image, how about you feed frame from another video per each new frame ? So you have video feed as input frames too, face aligner should detect where the face is per new frame. Turn off retageting and enable relative mode ,cause in "relative" mode its using whole input image and its using one image for entire video, im sure this can be changed so its using consecutive video frames instead of one image , so in theory it should be able to use different image per every frame and not just one image ?
> > > With this working we will be able to change what people say on the videos.
> > 
> > 
> > Yes, with some tweaks in the code, reading each frame from the video input as a source image seems to work. Thanks!
> 
> Can you post your ComfyUI workflow please?

`{
  "last_node_id": 32,
  "last_link_id": 69,
  "nodes": [
    {
      "id": 1,
      "type": "DownloadAndLoadLivePortraitModels",
      "pos": [
        144,
        218
      ],
      "size": {
        "0": 252,
        "1": 33.333343505859375
      },
      "flags": {},
      "order": 0,
      "mode": 0,
      "outputs": [
        {
          "name": "live_portrait_pipe",
          "type": "LIVEPORTRAITPIPE",
          "links": [
            58
          ],
          "shape": 3,
          "slot_index": 0
        }
      ],
      "properties": {
        "Node name for S&R": "DownloadAndLoadLivePortraitModels"
      }
    },
    {
      "id": 19,
      "type": "ImageResizeKJ",
      "pos": [
        507,
        675
      ],
      "size": {
        "0": 315,
        "1": 242
      },
      "flags": {},
      "order": 4,
      "mode": 0,
      "inputs": [
        {
          "name": "image",
          "type": "IMAGE",
          "link": 30
        },
        {
          "name": "get_image_size",
          "type": "IMAGE",
          "link": 68
        },
        {
          "name": "width_input",
          "type": "INT",
          "link": null,
          "widget": {
            "name": "width_input"
          }
        },
        {
          "name": "height_input",
          "type": "INT",
          "link": null,
          "widget": {
            "name": "height_input"
          }
        }
      ],
      "outputs": [
        {
          "name": "IMAGE",
          "type": "IMAGE",
          "links": [
            32
          ],
          "shape": 3,
          "slot_index": 0
        },
        {
          "name": "width",
          "type": "INT",
          "links": null,
          "shape": 3
        },
        {
          "name": "height",
          "type": "INT",
          "links": null,
          "shape": 3
        }
      ],
      "properties": {
        "Node name for S&R": "ImageResizeKJ"
      },
      "widgets_values": [
        512,
        512,
        "nearest-exact",
        false,
        2,
        0,
        0
      ]
    },
    {
      "id": 18,
      "type": "ImageConcatMulti",
      "pos": [
        860,
        679
      ],
      "size": {
        "0": 210,
        "1": 150
      },
      "flags": {},
      "order": 5,
      "mode": 0,
      "inputs": [
        {
          "name": "image_1",
          "type": "IMAGE",
          "link": 32
        },
        {
          "name": "image_2",
          "type": "IMAGE",
          "link": 67
        }
      ],
      "outputs": [
        {
          "name": "images",
          "type": "IMAGE",
          "links": [
            64
          ],
          "shape": 3,
          "slot_index": 0
        }
      ],
      "properties": {},
      "widgets_values": [
        2,
        "right",
        false,
        null
      ]
    },
    {
      "id": 30,
      "type": "LivePortraitProcess",
      "pos": [
        500,
        249
      ],
      "size": {
        "0": 367.79998779296875,
        "1": 338
      },
      "flags": {},
      "order": 3,
      "mode": 0,
      "inputs": [
        {
          "name": "pipeline",
          "type": "LIVEPORTRAITPIPE",
          "link": 58
        },
        {
          "name": "source_image",
          "type": "IMAGE",
          "link": 69
        },
        {
          "name": "driving_images",
          "type": "IMAGE",
          "link": 60
        }
      ],
      "outputs": [
        {
          "name": "cropped_images",
          "type": "IMAGE",
          "links": [],
          "shape": 3,
          "slot_index": 0
        },
        {
          "name": "full_images",
          "type": "IMAGE",
          "links": [
            67,
            68
          ],
          "shape": 3,
          "slot_index": 1
        }
      ],
      "properties": {
        "Node name for S&R": "LivePortraitProcess"
      },
      "widgets_values": [
        512,
        2.3,
        0,
        -0.125,
        true,
        true,
        1,
        true,
        1,
        true,
        true
      ]
    },
    {
      "id": 8,
      "type": "VHS_LoadVideo",
      "pos": [
        161,
        714
      ],
      "size": [
        235.1999969482422,
        491.1999969482422
      ],
      "flags": {},
      "order": 1,
      "mode": 0,
      "inputs": [
        {
          "name": "meta_batch",
          "type": "VHS_BatchManager",
          "link": null
        },
        {
          "name": "vae",
          "type": "VAE",
          "link": null
        }
      ],
      "outputs": [
        {
          "name": "IMAGE",
          "type": "IMAGE",
          "links": [
            30,
            60
          ],
          "shape": 3,
          "slot_index": 0
        },
        {
          "name": "frame_count",
          "type": "INT",
          "links": null,
          "shape": 3
        },
        {
          "name": "audio",
          "type": "VHS_AUDIO",
          "links": null,
          "shape": 3
        },
        {
          "name": "video_info",
          "type": "VHS_VIDEOINFO",
          "links": null,
          "shape": 3
        }
      ],
      "properties": {
        "Node name for S&R": "VHS_LoadVideo"
      },
      "widgets_values": {
        "video": "d1.mp4",
        "force_rate": 0,
        "force_size": "Disabled",
        "custom_width": 512,
        "custom_height": 512,
        "frame_load_cap": 32,
        "skip_first_frames": 0,
        "select_every_nth": 1,
        "choose video to upload": "image",
        "videopreview": {
          "hidden": false,
          "paused": false,
          "params": {
            "frame_load_cap": 32,
            "skip_first_frames": 0,
            "force_rate": 0,
            "filename": "d1.mp4",
            "type": "input",
            "format": "video/mp4",
            "select_every_nth": 1
          }
        }
      }
    },
    {
      "id": 23,
      "type": "VHS_VideoCombine",
      "pos": [
        1098,
        240
      ],
      "size": [
        1253.234130859375,
        310
      ],
      "flags": {},
      "order": 6,
      "mode": 0,
      "inputs": [
        {
          "name": "images",
          "type": "IMAGE",
          "link": 64
        },
        {
          "name": "audio",
          "type": "VHS_AUDIO",
          "link": null
        },
        {
          "name": "meta_batch",
          "type": "VHS_BatchManager",
          "link": null
        },
        {
          "name": "vae",
          "type": "VAE",
          "link": null
        }
      ],
      "outputs": [
        {
          "name": "Filenames",
          "type": "VHS_FILENAMES",
          "links": null,
          "shape": 3
        }
      ],
      "properties": {
        "Node name for S&R": "VHS_VideoCombine"
      },
      "widgets_values": {
        "frame_rate": 24,
        "loop_count": 0,
        "filename_prefix": "LivePortrait",
        "format": "video/h264-mp4",
        "pix_fmt": "yuv420p",
        "crf": 19,
        "save_metadata": true,
        "pingpong": false,
        "save_output": false,
        "videopreview": {
          "hidden": false,
          "paused": false,
          "params": {
            "filename": "LivePortrait_00005.mp4",
            "subfolder": "",
            "type": "temp",
            "format": "video/h264-mp4",
            "frame_rate": 24
          }
        }
      }
    },
    {
      "id": 32,
      "type": "VHS_LoadVideo",
      "pos": [
        -144,
        520
      ],
      "size": [
        235.1999969482422,
        387.63112233626396
      ],
      "flags": {},
      "order": 2,
      "mode": 0,
      "inputs": [
        {
          "name": "meta_batch",
          "type": "VHS_BatchManager",
          "link": null
        },
        {
          "name": "vae",
          "type": "VAE",
          "link": null
        }
      ],
      "outputs": [
        {
          "name": "IMAGE",
          "type": "IMAGE",
          "links": [
            69
          ],
          "shape": 3,
          "slot_index": 0
        },
        {
          "name": "frame_count",
          "type": "INT",
          "links": null,
          "shape": 3
        },
        {
          "name": "audio",
          "type": "VHS_AUDIO",
          "links": null,
          "shape": 3
        },
        {
          "name": "video_info",
          "type": "VHS_VIDEOINFO",
          "links": null,
          "shape": 3
        }
      ],
      "properties": {
        "Node name for S&R": "VHS_LoadVideo"
      },
      "widgets_values": {
        "video": "ssstwitter.com_1718714635436.mp4",
        "force_rate": 0,
        "force_size": "Disabled",
        "custom_width": 512,
        "custom_height": 512,
        "frame_load_cap": 32,
        "skip_first_frames": 0,
        "select_every_nth": 1,
        "choose video to upload": "image",
        "videopreview": {
          "hidden": false,
          "paused": false,
          "params": {
            "frame_load_cap": 32,
            "skip_first_frames": 0,
            "force_rate": 0,
            "filename": "ssstwitter.com_1718714635436.mp4",
            "type": "input",
            "format": "video/mp4",
            "select_every_nth": 1
          }
        }
      }
    }
  ],
  "links": [
    [
      30,
      8,
      0,
      19,
      0,
      "IMAGE"
    ],
    [
      32,
      19,
      0,
      18,
      0,
      "IMAGE"
    ],
    [
      58,
      1,
      0,
      30,
      0,
      "LIVEPORTRAITPIPE"
    ],
    [
      60,
      8,
      0,
      30,
      2,
      "IMAGE"
    ],
    [
      64,
      18,
      0,
      23,
      0,
      "IMAGE"
    ],
    [
      67,
      30,
      1,
      18,
      1,
      "IMAGE"
    ],
    [
      68,
      30,
      1,
      19,
      1,
      "IMAGE"
    ],
    [
      69,
      32,
      0,
      30,
      1,
      "IMAGE"
    ]
  ],
  "groups": [],
  "config": {},
  "extra": {
    "ds": {
      "scale": 1,
      "offset": {
        "0": 601,
        "1": -198
      }
    }
  },
  "version": 0.4
}`

not perfect only 32 frame

**Comment by cheezecrisp** [comment]
There is a dumb way to do this. Put the node 'image batch to image list'(Impack Pack) before source_image and put the node 'image list to image batch' after output. With this setting the workflow will produce a matrix of images, then pick out the images on the diagonal of the matrix, those images are exactly the frames what we want. 
But it's very inefficient, it will take much time to produce the matrix. Wanna know if there is a better way.

**Comment by kijai** [comment]
The video editing is mostly working in the develop branch already, just some bugs to squash and optimizations to do.

**Comment by skydam** [comment]
I can only see Source Image as input for the node (in Develop branch), no video option yet. What am I missing?

**Comment by kijai** [comment]
> I can only see Source Image as input for the node (in Develop branch), no video option yet. What am I missing?

The version in the develop branch takes both single image or a batch of images.

**Comment by skydam** [comment]
Thanks! I'm looking at the new node, but a. what's the input node for crop_info? That's a new one, and b. which input node would one use as batch input for source image? BTW love your work!

**Comment by skydam** [comment]
Sorry, beginner here. I'm seeing crop_info = self.cropper.crop_single_image(img_rgb), but Cropper seems commented out in #from .utils.cropper import Cropper

**Comment by kijai** [comment]
> Sorry, beginner here. I'm seeing crop_info = self.cropper.crop_single_image(img_rgb), but Cropper seems commented out in #from .utils.cropper import Cropper

It's a whole new structure in that version, there's separate node that does the detection and cropping, it outputs the crop info for the main node. You input your source to the cropper node, it can be single image or batch of images, then you input the driving video to the process node.

**Comment by skydam** [comment]
Ah I see! Yes, found it: LivePortraitCropper. Thanks!

**Comment by skydam** [comment]
It's working! The cropped images work fine. The full images is still a mess for me though. Not quite sure if I'm doing it wrong or if it's still work in progress.

**Comment by skydam** [comment]
https://github.com/kijai/ComfyUI-LivePortraitKJ/assets/73529516/188c4279-8ea7-49a9-9e8b-fba82f1a8109

**Comment by Maelstrom2014** [comment]
> LivePortrait_00008.mp4

Please post example! or screenshot of workflow.

**Comment by skydam** [comment]
https://github.com/kijai/ComfyUI-LivePortraitKJ/assets/73529516/25f0c47d-c4e9-46d8-91b5-3df0f2829f20

This is what comes out of full_images, whereas the cropped (stabilised) images are as above.

**Comment by skydam** [comment]
![CleanShot 2024-07-10 at 00 08 27@2x](https://github.com/kijai/ComfyUI-LivePortraitKJ/assets/73529516/a7fd7619-739f-4b3a-9834-203e2a76d417)

**Comment by kijai** [comment]
> ![CleanShot 2024-07-10 at 00 08 27@2x](https://private-user-images.githubusercontent.com/73529516/347162333-a7fd7619-739f-4b3a-9834-203e2a76d417.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA1NjM4MzAsIm5iZiI6MTcyMDU2MzUzMCwicGF0aCI6Ii83MzUyOTUxNi8zNDcxNjIzMzMtYTdmZDc2MTktNzM5Zi00YjNhLTk4MzQtMjAzZTJhNzZkNDE3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA5VDIyMTg1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk5OWQwYTljNTVlMWJmZWU0NWRjNmEzNWYzNDljMGIwZjQxMDdmMWEzMDJkMDRlMjY2ODA5NTQ3NDBmNGU1MDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.6F39XCImk8xyyICQBWtVrcRRSiEELI2XTTx15eRNizc)

What are you feeding for the source_image there? it should be the input video, not the crop

**Comment by skydam** [comment]
THAT WAS IT! I fed the cropped image into source. 

https://github.com/kijai/ComfyUI-LivePortraitKJ/assets/73529516/10b1ae04-013d-4ab7-a2c5-6ac27b8d301e

**Comment by Maelstrom2014** [comment]
need also a mask for pasting image.

**Comment by Maelstrom2014** [comment]
LivePortraitCropper still use CPU, takes 160sec, too long. I does not matter that i put CUDA in menu

**Comment by kijai** [comment]
> LivePortraitCropper still use CPU, takes 160sec, too long. I does not matter that i put CUDA in menu

Possibly you don't have onnx installed for GPU? Do you have onnxruntime-gpu installed? It's sometimes bit of a pain to get to work, for reference on my 4090 it's about 33it/s.

**Comment by skydam** [comment]
I have 2.75it/s on my 3090/24gb

**Comment by paulovasconcellos-hotmart** [comment]
> THAT WAS IT! I fed the cropped image into source.
> 
>  LivePortrait_00019.mp4

Hi @skydam Can you post the screenshot of the whole workflow for this video, please?

**Comment by serkandyck** [comment]
> > THAT WAS IT! I fed the cropped image into source.
> > LivePortrait_00019.mp4
> 
> Hi @skydam Can you post the screenshot of the whole workflow for this video, please?

also you can get your workflow json with this button

![image](https://github.com/kijai/ComfyUI-LivePortraitKJ/assets/12444059/bc5a1c08-1d72-45ea-877b-a7dd8c3bd304)

**Comment by skydam** [comment]
[LivePortraitVideoInput (1).json](https://github.com/user-attachments/files/16163685/LivePortraitVideoInput.1.json)
Enjoy! Remember, this was done with the new nodes that are used in the develop branch.

**Comment by androideve** [comment]
> [LivePortraitVideoInput (1).json](https://github.com/user-attachments/files/16163685/LivePortraitVideoInput.1.json) Enjoy! Remember, this was done with the new nodes that are used in the develop branch.

TY for providing a workflow! Unfortunately this one doesn't have any of the node connections on my end. Can you confirm on your end that this workflow is loading with the connections?

**Comment by kijai** [comment]
Merged to main
