### ISSUE TITLE
No such file or directory appearance_feature_extractor.pth

### ISSUE THREAD

**Issue by amit4aws** [kijai/ComfyUI-LivePortraitKJ#80]
Any idea why i am seeing this while running the queue prompt

`!!! Exception during processing!!! [Errno 2] No such file or directory: 'D:\\Home\\Neo\\Tech\\workspace\\AI\\AI_Vision\\ComfyUI\\ComfyUI_windows_portable\\ComfyUI\\models\\liveportrait\\base_models\\appearance_feature_extractor.pth'
`

**Comment by kijai** [comment]
That's not an error from these nodes as I use .safetensors and not .pth models.

Probably mixing up with the other LivePortrait nodes?

**Comment by amit4aws** [comment]
I have just one node for liveportrait
![image](https://github.com/user-attachments/assets/4d76490b-2353-455b-b7b8-f26913ab723b)

under it i have all the required tensor files in it
![image](https://github.com/user-attachments/assets/4f8e90e3-3c51-4f32-aca0-ad879a834b2a)

**Comment by amit4aws** [comment]
@kijai  Is it because the missing nodes were installed from the provided option at comfyUI ? node seems to be from different author

![image](https://github.com/user-attachments/assets/6ea50bdb-0657-41c4-86b1-8704fc1ad4fe)

**Comment by kijai** [comment]
> @kijai  Is it because the missing nodes were installed from the provided option at comfyUI ? node seems to be from different author
> 
> ![image](https://github.com/user-attachments/assets/6ea50bdb-0657-41c4-86b1-8704fc1ad4fe)
> 

Yes, unless they switched to use the files I converted, those models won't work with their nodes.

**Comment by amit4aws** [comment]
> > @kijai  Is it because the missing nodes were installed from the provided option at comfyUI ? node seems to be from different author
> > ![image](https://private-user-images.githubusercontent.com/32779181/350810280-6ea50bdb-0657-41c4-86b1-8704fc1ad4fe.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE2NDE3NjAsIm5iZiI6MTcyMTY0MTQ2MCwicGF0aCI6Ii8zMjc3OTE4MS8zNTA4MTAyODAtNmVhNTBiZGItMDY1Ny00MWM0LTg2YjEtODcwNGZjMWFkNGZlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzIyVDA5NDQyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA2NzBjZjE0ZTNlZjM4ZmQ2ODAxZGIzYjFkODI1Njc0OTkwNzY1ZjEzYTE0MjA4NmZjODM5OGVmNjZiYTk5ZjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.mFpytQirHjDdCd52aW0RHFMZr5n-XoTxJp2DFFdo7m8)
> 
> Yes, unless they switched to use the files I converted, those models won't work with their nodes.

how is it working for you then? are you using different nodes in your workflow

**Comment by kijai** [comment]
> > > @kijai  Is it because the missing nodes were installed from the provided option at comfyUI ? node seems to be from different author
> > > ![image](https://private-user-images.githubusercontent.com/32779181/350810280-6ea50bdb-0657-41c4-86b1-8704fc1ad4fe.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE2NDE3NjAsIm5iZiI6MTcyMTY0MTQ2MCwicGF0aCI6Ii8zMjc3OTE4MS8zNTA4MTAyODAtNmVhNTBiZGItMDY1Ny00MWM0LTg2YjEtODcwNGZjMWFkNGZlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzIyVDA5NDQyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA2NzBjZjE0ZTNlZjM4ZmQ2ODAxZGIzYjFkODI1Njc0OTkwNzY1ZjEzYTE0MjA4NmZjODM5OGVmNjZiYTk5ZjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.mFpytQirHjDdCd52aW0RHFMZr5n-XoTxJp2DFFdo7m8)
> > 
> > 
> > Yes, unless they switched to use the files I converted, those models won't work with their nodes.
> 
> how is it working for you then? are you using different nodes in your workflow

These nodes have nothing to do with those nodes you show, completely separate package and workflows are not compatible.
