### ISSUE TITLE
source image detection threshold

### ISSUE THREAD

**Issue by handles98** [kijai/ComfyUI-LivePortraitKJ#90]
[Live Portrait Updates](https://github.com/KwaiVGI/LivePortrait/blob/main/assets/docs/changelog/2024-07-24.md)
Detection threshold: We have added a --det_thresh argument with a default value of 0.15 to increase recall, meaning more types of faces (e.g., monkeys, human-like) will be detected. You can set it to other values, e.g., 0.5, by using python app.py --det_thresh 0.5.

thx

**Comment by kijai** [comment]
Added.

Note that the alternative cropper "face_alignment" I added also can do animals better.
