### ISSUE TITLE
Failed on MacBook Pro m2 with "User specified an unsupported autocast device_type 'mps'"

### ISSUE THREAD

**Issue by peng2219** [kijai/ComfyUI-LivePortraitKJ#94]
I think  it's pytorch related,  maybe someone here could give me some suggestions? thanks.
I use latest version, and here are some env infomations.

- `transformers` version: 4.40.0
- Platform: macOS-14.5-arm64-arm-64bit
- Python version: 3.10.0
- Huggingface_hub version: 0.24.2
- Safetensors version: 0.4.3
- Accelerate version: 0.33.0
- Accelerate config: 	not found
- PyTorch version (GPU?): 2.3.1 (False)
- Tensorflow version (GPU?): not installed (NA)
- Flax version (CPU?/GPU?/TPU?): not installed (NA)
- Jax version: not installed
- JaxLib version: not installed
- Using GPU in script?: <fill in>
- Using distributed or parallel set-up in script?: <fill in> 

The detailed **logs** are here:

got prompt
Detecting, cropping, and processing..:   0%|                                  | 0/1 [00:00<?, ?it/s]
!!! Exception during processing!!! **User specified an unsupported autocast device_type 'mps'**
Traceback (most recent call last):
  File "/Users/peng/Code/ComfyUI/execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "/Users/peng/Code/ComfyUI/execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "/Users/peng/Code/ComfyUI/execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "/Users/peng/Code/ComfyUI/custom_nodes/ComfyUI-LivePortraitKJ/nodes.py", line 652, in process
    x_s_info = pipeline.live_portrait_wrapper.get_kp_info(I_s)
  File "/Users/peng/Code/ComfyUI/custom_nodes/ComfyUI-LivePortraitKJ/liveportrait/live_portrait_wrapper.py", line 71, in get_kp_info
    with torch.autocast(get_autocast_device(self.device_id), dtype=torch.float16) if self.cfg.flag_use_half_precision else nullcontext():
  File "/Users/peng/Code/miniconda3/envs/ComfyUI/lib/python3.10/site-packages/torch/amp/autocast_mode.py", line 241, in __init__
    raise RuntimeError(
**RuntimeError: User specified an unsupported autocast device_type 'mps'**

Prompt executed in 0.16 seconds

**Comment by kijai** [comment]
Have to use fp32 as dtype on the loader node on Mac, or auto, which it should have been but I may have forgotten it on fp16 in the example workflow.

**Comment by peng2219** [comment]
> Have to use fp32 as dtype on the loader node on Mac, or auto, which it should have been but I may have forgotten it on fp16 in the example workflow.

@kijai It worked, thanks!
