### ISSUE TITLE
X-Pose for keypoints？

### ISSUE THREAD

**Issue by singlinhaha** [kijai/ComfyUI-LivePortraitKJ#95]
I have seen other developers using X-Pose for keypoints，and easy to ues LivePortrait on animal face. I'm not very familiar with it. It is possible to integrate an X-Pose detector into the current workflow？
repository link：https://github.com/ShiJiaying/LivePortrait/tree/main

**Comment by kijai** [comment]
It is possible, installing xpose and all it's dependencies seem a bit daunting and is really the only issue implementing it. Might look at it at some point, meanwhile the new Insightface threshold option or the face_alignment -detector do help with animal faces some.

**Comment by singlinhaha** [comment]
Thank you for your response!!!

**Comment by brayevalerien** [comment]
Hey this would be huge, it would mean vid2vid support for animals! Do you plan on implementing it @kijai ? If not is there a way I can help?

**Comment by zeroooi** [comment]
It's 2025, is there any progress on this project? I need the official xpose as a comfyUI node in my daily life🙏🙏
